"""Temporarily remoce created_at

Revision ID: c25d44296cdc
Revises: 453f31f87f50
Create Date: 2026-03-09 17:54:08.096875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c25d44296cdc'
down_revision = '453f31f87f50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
